In [4]:
from pyedflib import highlevel
import pandas as pd
import numpy as np
from glob import glob

data_list=glob('./data/sleep-cassette/*.edf')

trains=[x for x in data_list if x.endswith('PSG.edf')]
labels=[x for x in data_list if x.endswith('Hypnogram.edf')]

data_list

['./data/sleep-cassette\\SC4001E0-PSG.edf',
 './data/sleep-cassette\\SC4001EC-Hypnogram.edf',
 './data/sleep-cassette\\SC4002E0-PSG.edf',
 './data/sleep-cassette\\SC4002EC-Hypnogram.edf',
 './data/sleep-cassette\\SC4011E0-PSG.edf',
 './data/sleep-cassette\\SC4011EH-Hypnogram.edf',
 './data/sleep-cassette\\SC4012E0-PSG.edf',
 './data/sleep-cassette\\SC4012EC-Hypnogram.edf',
 './data/sleep-cassette\\SC4021E0-PSG.edf',
 './data/sleep-cassette\\SC4021EH-Hypnogram.edf',
 './data/sleep-cassette\\SC4022E0-PSG.edf',
 './data/sleep-cassette\\SC4022EJ-Hypnogram.edf',
 './data/sleep-cassette\\SC4031E0-PSG.edf',
 './data/sleep-cassette\\SC4031EC-Hypnogram.edf',
 './data/sleep-cassette\\SC4032E0-PSG.edf',
 './data/sleep-cassette\\SC4032EP-Hypnogram.edf',
 './data/sleep-cassette\\SC4041E0-PSG.edf',
 './data/sleep-cassette\\SC4041EC-Hypnogram.edf',
 './data/sleep-cassette\\SC4042E0-PSG.edf',
 './data/sleep-cassette\\SC4042EC-Hypnogram.edf',
 './data/sleep-cassette\\SC4051E0-PSG.edf',
 './data/sleep-c

In [7]:
highlevel.read_edf(trains[0])

([array([ 5.01684982, -2.57875458,  1.35970696, ...,  5.2981685 ,
         -4.64175824,  6.61098901]),
  array([-2.46739927,  1.46739927, -4.0989011 , ..., -3.04322344,
         -3.71501832,  1.75531136]),
  array([ 16.50866911,  16.01587302,   9.60952381, ...,  69.73064713,
          80.57216117, 102.25518926]),
  array([-482.,  628.,  -95., ...,  145.,  100.,  125.]),
  array([3.552, 3.49 , 3.476, ..., 3.546, 3.666, 3.582]),
  array([37.20645161, 37.22795699, 37.23655914, ..., 37.43978495,
         37.45053763, 37.43225806]),
  array([920., 899., 919., ..., 884., 898., 898.])],
 [{'label': 'EEG Fpz-Cz',
   'dimension': 'uV',
   'sample_rate': 100.0,
   'sample_frequency': 100.0,
   'physical_max': 192.0,
   'physical_min': -192.0,
   'digital_max': 2047,
   'digital_min': -2048,
   'prefilter': 'HP:0.5Hz LP:100Hz [enhanced cassette BW]',
   'transducer': 'Ag-AgCl electrodes'},
  {'label': 'EEG Pz-Oz',
   'dimension': 'uV',
   'sample_rate': 100.0,
   'sample_frequency': 100.0,
   'ph

In [37]:
df = pd.DataFrame(highlevel.read_edf(trains[0])[0]).T
df.columns = ['EEG Fpz-Cz', 'EEG Pz-Oz', 'EOG horizontal', 'Resp oro-nassal',
              'EMG submental', 'Temp rectal', 'Event marker']
df

KeyboardInterrupt: 

In [10]:
highlevel.read_edf(labels[0])

(array([], dtype=float64),
 [],
 {'technician': '',
  'recording_additional': '',
  'patientname': 'Female 33yr',
  'patient_additional': '',
  'patientcode': '',
  'equipment': '',
  'admincode': '',
  'sex': 'Female',
  'startdate': datetime.datetime(1989, 4, 24, 16, 13),
  'birthdate': '',
  'gender': 'Female',
  'annotations': [[0.0, 30630.0, 'Sleep stage W'],
   [30630.0, 120.0, 'Sleep stage 1'],
   [30750.0, 390.0, 'Sleep stage 2'],
   [31140.0, 30.0, 'Sleep stage 3'],
   [31170.0, 30.0, 'Sleep stage 2'],
   [31200.0, 150.0, 'Sleep stage 3'],
   [31350.0, 30.0, 'Sleep stage 4'],
   [31380.0, 60.0, 'Sleep stage 3'],
   [31440.0, 60.0, 'Sleep stage 4'],
   [31500.0, 30.0, 'Sleep stage 3'],
   [31530.0, 120.0, 'Sleep stage 4'],
   [31650.0, 30.0, 'Sleep stage 3'],
   [31680.0, 120.0, 'Sleep stage 4'],
   [31800.0, 30.0, 'Sleep stage W'],
   [31830.0, 60.0, 'Sleep stage 3'],
   [31890.0, 60.0, 'Sleep stage 2'],
   [31950.0, 120.0, 'Sleep stage 3'],
   [32070.0, 30.0, 'Sleep stage 4']

In [31]:
df1 = pd.DataFrame(highlevel.read_edf(labels[0])[2]['annotations'])
df1.columns=['time', 'duration', 'sleep_stage']
df1[80:]
# 0초 부터 30630초 까지 Sleep stage W

time  duration    sleep_stage
80   40290.0      30.0  Sleep stage 1
81   40320.0     180.0  Sleep stage 2
82   40500.0     870.0  Sleep stage R
83   41370.0      30.0  Sleep stage 2
84   41400.0      60.0  Sleep stage 1
..       ...       ...            ...
149  51540.0      30.0  Sleep stage 1
150  51570.0     540.0  Sleep stage W
151  52110.0     150.0  Sleep stage 1
152  52260.0   27240.0  Sleep stage W
153  79500.0    6900.0  Sleep stage ?

[74 rows x 3 columns]