In [47]:
from pyedflib import highlevel
import pandas as pd
import numpy as np
from glob import glob

data_list=glob('./data/data2022/*.edf')

# trains=[x for x in data_list if x.endswith('PSG.edf')]
# labels=[x for x in data_list if x.endswith('Hypnogram.edf')]
trains=[x for x in data_list if not x.endswith('_sleepscoring.edf')]
labels=[x for x in data_list if x.endswith('_sleepscoring.edf')]

data_list

['./data/data2022/SN001.edf',
 './data/data2022/SN001_sleepscoring.edf',
 './data/data2022/SN002.edf',
 './data/data2022/SN002_sleepscoring.edf',
 './data/data2022/SN003.edf',
 './data/data2022/SN003_sleepscoring.edf',
 './data/data2022/SN004.edf',
 './data/data2022/SN004_sleepscoring.edf',
 './data/data2022/SN005.edf',
 './data/data2022/SN005_sleepscoring.edf',
 './data/data2022/SN006.edf',
 './data/data2022/SN006_sleepscoring.edf',
 './data/data2022/SN007.edf',
 './data/data2022/SN007_sleepscoring.edf',
 './data/data2022/SN008.edf',
 './data/data2022/SN008_sleepscoring.edf',
 './data/data2022/SN009.edf',
 './data/data2022/SN009_sleepscoring.edf',
 './data/data2022/SN010.edf',
 './data/data2022/SN010_sleepscoring.edf',
 './data/data2022/SN011.edf',
 './data/data2022/SN011_sleepscoring.edf',
 './data/data2022/SN012.edf',
 './data/data2022/SN012_sleepscoring.edf',
 './data/data2022/SN013.edf',
 './data/data2022/SN013_sleepscoring.edf',
 './data/data2022/SN015.edf',
 './data/data2022/SN0

In [49]:
print(len(trains))
print(len(labels))

151
151


In [52]:
highlevel.read_edf(trains[0])

(array([[ 1.71267262e+01,  1.82253758e+01,  1.75906004e+01, ...,
         -1.22072175e-02, -1.22072175e-02, -1.22072175e-02],
        [ 1.47585260e+01,  1.55642023e+01,  1.06324865e+01, ...,
         -1.22072175e-02, -1.22072175e-02, -1.22072175e-02],
        [ 3.83428702e+01,  3.71221485e+01,  2.41092546e+01, ...,
         -1.22072175e-02, -1.22072175e-02, -1.22072175e-02],
        ...,
        [ 3.74761578e+00,  1.09987030e+01,  2.16433967e+01, ...,
         -1.22072175e-02, -1.22072175e-02, -1.22072175e-02],
        [-9.28969253e+00, -1.09010452e+01, -9.50942245e+00, ...,
         -1.22072175e-02, -1.22072175e-02, -1.22072175e-02],
        [ 7.37193866e+01,  7.09361410e+01,  6.93980316e+01, ...,
         -3.66216526e-02, -3.66216526e-02, -3.66216526e-02]]),
 [{'label': 'EEG F4-M1',
   'dimension': 'uV',
   'sample_rate': 256.0,
   'sample_frequency': 256.0,
   'physical_max': 800.0,
   'physical_min': -800.0,
   'digital_max': 32767,
   'digital_min': -32768,
   'prefilter': 'HP:0.2

In [53]:
df = pd.DataFrame(highlevel.read_edf(trains[0])[0]).T
df.columns = ['EEG Fpz-Cz', 'EEG Pz-Oz', 'EOG horizontal', 'Resp oro-nassal',
              'EMG submental', 'Temp rectal', 'Event marker']
df

ValueError: Length mismatch: Expected axis has 8 elements, new values have 7 elements

In [55]:
highlevel.read_edf(labels[0])

(array([], dtype=float64),
 [],
 {'technician': '',
  'recording_additional': '',
  'patientname': 'X',
  'patient_additional': '',
  'patientcode': 'SN001',
  'equipment': '',
  'admincode': '',
  'sex': '',
  'startdate': datetime.datetime(2001, 1, 1, 23, 59, 30),
  'birthdate': '',
  'gender': '',
  'annotations': [[0.0, 30.0, 'Sleep stage W'],
   [30.0, 30.0, 'Sleep stage W'],
   [33.43, 0.0, 'Lights off@@EEG F4-A1'],
   [60.0, 30.0, 'Sleep stage W'],
   [90.0, 30.0, 'Sleep stage W'],
   [120.0, 30.0, 'Sleep stage W'],
   [150.0, 30.0, 'Sleep stage W'],
   [180.0, 30.0, 'Sleep stage W'],
   [210.0, 30.0, 'Sleep stage W'],
   [240.0, 30.0, 'Sleep stage N1'],
   [270.0, 30.0, 'Sleep stage N1'],
   [300.0, 30.0, 'Sleep stage N1'],
   [330.0, 30.0, 'Sleep stage N1'],
   [360.0, 30.0, 'Sleep stage N1'],
   [390.0, 30.0, 'Sleep stage N1'],
   [420.0, 30.0, 'Sleep stage N1'],
   [450.0, 30.0, 'Sleep stage N1'],
   [480.0, 30.0, 'Sleep stage N2'],
   [510.0, 30.0, 'Sleep stage N1'],
   [54

In [9]:
highlevel.read_edf(labels[0])[2]

{'technician': '',
 'recording_additional': '',
 'patientname': 'Female 33yr',
 'patient_additional': '',
 'patientcode': '',
 'equipment': '',
 'admincode': '',
 'sex': 'Female',
 'startdate': datetime.datetime(1989, 4, 24, 16, 13),
 'birthdate': '',
 'gender': 'Female',
 'annotations': [[0.0, 30630.0, 'Sleep stage W'],
  [30630.0, 120.0, 'Sleep stage 1'],
  [30750.0, 390.0, 'Sleep stage 2'],
  [31140.0, 30.0, 'Sleep stage 3'],
  [31170.0, 30.0, 'Sleep stage 2'],
  [31200.0, 150.0, 'Sleep stage 3'],
  [31350.0, 30.0, 'Sleep stage 4'],
  [31380.0, 60.0, 'Sleep stage 3'],
  [31440.0, 60.0, 'Sleep stage 4'],
  [31500.0, 30.0, 'Sleep stage 3'],
  [31530.0, 120.0, 'Sleep stage 4'],
  [31650.0, 30.0, 'Sleep stage 3'],
  [31680.0, 120.0, 'Sleep stage 4'],
  [31800.0, 30.0, 'Sleep stage W'],
  [31830.0, 60.0, 'Sleep stage 3'],
  [31890.0, 60.0, 'Sleep stage 2'],
  [31950.0, 120.0, 'Sleep stage 3'],
  [32070.0, 30.0, 'Sleep stage 4'],
  [32100.0, 30.0, 'Sleep stage 3'],
  [32130.0, 120.0, 'Sle

In [33]:
df1 = pd.DataFrame(highlevel.read_edf(labels[0])[2]['annotations'])
df1.columns=['time', 'duration', 'sleep_stage']
df1
# 0초 부터 30630초 까지 Sleep stage W

time  duration    sleep_stage
0        0.0   30630.0  Sleep stage W
1    30630.0     120.0  Sleep stage 1
2    30750.0     390.0  Sleep stage 2
3    31140.0      30.0  Sleep stage 3
4    31170.0      30.0  Sleep stage 2
..       ...       ...            ...
149  51540.0      30.0  Sleep stage 1
150  51570.0     540.0  Sleep stage W
151  52110.0     150.0  Sleep stage 1
152  52260.0   27240.0  Sleep stage W
153  79500.0    6900.0  Sleep stage ?

[154 rows x 3 columns]

In [8]:
import os
from glob import glob

psg_fnames = glob(os.path.join('./data/data2013/', "*PSG.edf"))

f = open(psg_fnames[0], 'r', encoding='ISO-8859-1')

# print(f.tell())  # check file position
print(f.tell() == 0)  # check file position
print(f.read(8) == '0       ')
# print(f.read(8) == '0       ')

True
True


In [14]:
import numpy as np
data = np.load('./data/data2013/eeg_fpg_cz/SC4272F0.npz', allow_pickle=True)

for i in data:
    print(i)
    print(data[i])

x
[[[ 1.1765324e-03]
  [ 1.0187301e-03]
  [ 2.2971917e-04]
  ...
  [ 2.9108670e-04]
  [ 1.4395360e-03]
  [ 5.4532359e-04]]

 [[ 1.2729671e-03]
  [-7.9599512e-04]
  [ 1.4044689e-03]
  ...
  [ 5.3655676e-04]
  [ 2.2285471e-03]
  [ 5.8039074e-04]]

 [[ 1.9304762e-03]
  [ 6.8559218e-04]
  [ 2.5441514e-03]
  ...
  [ 1.2451770e-04]
  [-9.9763123e-04]
  [ 5.4532359e-04]]

 ...

 [[-6.9502806e-03]
  [-9.5364833e-03]
  [-6.1963368e-03]
  ...
  [-1.9985349e-04]
  [ 2.7019535e-03]
  [ 2.0341881e-04]]

 [[ 4.1660075e-03]
  [ 5.1902322e-04]
  [ 3.1490598e-03]
  ...
  [-3.8395604e-04]
  [ 1.0187301e-03]
  [-7.7118435e-05]]

 [[ 1.4307692e-03]
  [ 1.9465202e-04]
  [ 1.3431014e-03]
  ...
  [ 2.8231990e-04]
  [-1.0326984e-03]
  [ 7.8202685e-04]]]
y
[0 0 0 ... 0 0 0]
fs
100.0
ch_label
EEG Fpz-Cz
header_raw
{'local_subject_id': 'X F X Female_54yr', 'local_recording_id': 'Startdate 02-APR-1990 X X X', 'date_time': '2090-04-02 12:15:00', 'EDF+': False, 'contiguous': True, 'n_records': 2870, 'record_length'

In [20]:
import os
from mne import Epochs, pick_types, find_events
from mne.io import concatenate_raws, read_raw_edf

psg_fnames = glob(os.path.join('./data/data2013/', "*PSG.edf"))
np.asarray(psg_fnames)
i = 0
select_ch='EEG Fpz-Cz'
raw = read_raw_edf(psg_fnames[i], preload=True, stim_channel=None)
sampling_rate = raw.info['sfreq']

raw_ch_df = raw.to_data_frame(scalings=100.0)[select_ch]
raw_ch_df = raw_ch_df.to_frame()
raw_ch_df.set_index(np.arange(len(raw_ch_df)))

print('raw')
display(raw)
print('sampling_rate')
display(sampling_rate)
print('raw_ch_df')
display(raw_ch_df)

Extracting EDF parameters from /mnt/d/home/GoodSleep/data/data2013/SC4001E0-PSG.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 7949999  =      0.000 ... 79499.990 secs...
raw


<RawEDF | SC4001E0-PSG.edf, 7 x 7950000 (79500.0 s), ~424.6 MB, data loaded>

sampling_rate


100.0

raw_ch_df


EEG Fpz-Cz
0          0.000502
1         -0.000258
2          0.000136
3         -0.000239
4         -0.000520
...             ...
7949995    0.001130
7949996    0.000361
7949997    0.000530
7949998   -0.000464
7949999    0.000661

[7950000 rows x 1 columns]

In [92]:
import os
from datetime import datetime
from dataloader import SeqDataLoader
import time
import numpy as np
from imblearn.over_sampling import SMOTE

num_folds = 20
data_dir = 'data/data2013/eeg_fpz_cz'
classes = ['W', 'N1', 'N2', 'N3', 'REM']
checkpoint_dir = 'checkpoints-seq2seq-sleep-EDF'
output_dir = 'outputs_2013/outputs_eeg_fpz_cz'

hparams = {
    'epochs': 120,
    'batch_size': 20,
    'num_units': 128,
    'embed_size': 10,
    'input_depth': 3000,
    'n_channels': 100,
    'bidirectional': True,
    'use_attention': True,
    'lstm_layers': 2,
    'attention_size': 64,
    'beam_width': 4,
    'use_beamsearch_decode': False,
    'max_time_step': 10,
    'output_max_length': 10 + 2,
    'akara2017': True,
    'test_step': 5
}

path, channel_ename = os.path.split(data_dir)
traindata_dir = os.path.join(os.path.abspath(os.path.join(data_dir, os.pardir)),'traindata/')

print(path)
print(channel_ename)
print(traindata_dir)

print((str(datetime.now())))

data/data2013
eeg_fpz_cz
d:\sejin\GoodSleep\data\data2013\traindata/
2023-12-06 16:33:06.775158


In [93]:
fold_idx = 0

start_time_fold_i = time.time()
data_loader = SeqDataLoader(data_dir, num_folds, fold_idx, classes=classes)
X_train, y_train, X_test, y_test = data_loader.load_data(seq_len=hparams['max_time_step'])

print(start_time_fold_i)
print(X_train)
print(y_train)
print(X_test)
print(y_test)


========== [Fold-0] ==========

Load training set:
Loading data/data2013/eeg_fpz_cz\SC4232E0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4271F0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4411E0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4292G0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4512E0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4061E0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4491G0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4601E0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4121E0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4172E0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4332F0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4171E0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4272F0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4822G0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4811G0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4311E0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4382F0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4742E0.npz ...
Loading data/data2013/eeg_fpz_cz\SC4362F0.npz ..

In [94]:
# preprocessing
char2numY = dict(list(zip(classes, list(range(len(classes))))))        
pre_f1_macro = 0

print(char2numY)

{'W': 0, 'N1': 1, 'N2': 2, 'N3': 3, 'REM': 4}


In [95]:
# <SOD> is a token to show start of decoding  and <EOD> is a token to indicate end of decoding
char2numY['<SOD>'] = len(char2numY)
char2numY['<EOD>'] = len(char2numY)
num2charY = dict(list(zip(list(char2numY.values()), list(char2numY.keys()))))

print(num2charY)

{0: 'W', 1: 'N1', 2: 'N2', 3: 'N3', 4: 'REM', 5: '<SOD>', 6: '<EOD>'}


In [96]:
# # over-sampling: SMOTE:
# X_train = np.reshape(X_train,[X_train.shape[0]*X_train.shape[1],-1])
# y_train= y_train.flatten()

# print('X_train')
# print(X_train)

# print('y_train')
# print(y_train)

In [97]:
# print(X_train.shape)
# print(X_test.shape)
# print(y_train.shape)
# print(y_test.shape)

In [98]:
nums = []
for cl in classes:
    nums.append(len(np.where(y_train == char2numY[cl])[0]))

print(nums)
if (os.path.exists(traindata_dir) == False):
    os.mkdir(traindata_dir)
fname = os.path.join(traindata_dir,'trainData_'+channel_ename+'_SMOTE_all_10s_f'+str(fold_idx)+'.npz')

[63673, 20639, 65555, 12354, 24719]


In [99]:

if (os.path.isfile(fname)):
    X_train, y_train,_ = data_loader.load_npz_file(fname)
else:
    # oversampling
    n_osamples = nums[2] - 7000
    ratio = {0: n_osamples if nums[0] < n_osamples else nums[0], 1: n_osamples if nums[1] < n_osamples else nums[1],
                2: nums[2], 3: n_osamples if nums[3] < n_osamples else nums[3], 4: n_osamples if nums[4] < n_osamples else nums[4]}

    sm = SMOTE(random_state=12, sampling_strategy=ratio)
    X_train, y_train = sm.fit_resample(X_train, y_train)
    data_loader.save_to_npz_file(X_train, y_train,data_loader.sampling_rate,fname)

    print(n_osamples)
    print(ratio)

In [100]:
X_train = X_train[:(X_train.shape[0] // hparams['max_time_step']) * hparams['max_time_step'], :]
y_train = y_train[:(X_train.shape[0] // hparams['max_time_step']) * hparams['max_time_step']]

X_train = np.reshape(X_train,[-1,X_test.shape[1],X_test.shape[2]])
y_train = np.reshape(y_train,[-1,y_test.shape[1],])

print(X_train.shape)
print(y_train.shape)

(30191, 10, 3000)
(30191, 10)


In [16]:
X_train[0][0]

array([0.72612983, 0.7783324 , 0.72612983, ..., 0.6608765 , 0.21715423,
       0.47816733], dtype=float32)

In [55]:
y_train[0]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [101]:
# shuffle training data_2013
permute = np.random.permutation(len(y_train))
X_train = X_train[permute]
y_train = y_train[permute]

In [18]:
X_train[0][0]

array([-0.5032782 , -0.43331504,  0.19317372, ..., -0.08667912,
       -0.3410908 ,  0.05324729], dtype=float32)

In [102]:
# add '<SOD>' to the beginning of each label sequence, and '<EOD>' to the end of each label sequence (both for training and test sets)
y_train= [[char2numY['<SOD>']] + [y_ for y_ in date] + [char2numY['<EOD>']] for date in y_train]
y_train = np.array(y_train)

y_test= [[char2numY['<SOD>']] + [y_ for y_ in date] + [char2numY['<EOD>']] for date in y_test]
y_test = np.array(y_test)

In [35]:
import torch

# NumPy 배열을 PyTorch 텐서로 변환
input_tensor = torch.from_numpy(X_train)

# 차원 추가 (30191, 10, 3000) -> (30191, 10, 3000, 1)
input_tensor = input_tensor.unsqueeze(-1)

input_tensor.shape

c:\Users\user\anaconda3\envs\test\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.Size([30191, 10, 3000, 1])

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# m = nn.Conv1d(10, 64, 400, stride=50)
input_ = torch.randn(7547, 10, 3000).to('cuda')
cnn1 = nn.Sequential(
    nn.Conv1d(10, 64, 50, stride=6),
    nn.ReLU(),
    nn.MaxPool1d(8, stride=8),
    nn.Dropout(0.5),
    nn.Conv1d(64, 128, 8, stride=1, padding='same'),
    nn.ReLU(),
    nn.Conv1d(128, 128, 8, stride=1, padding='same'),
    nn.ReLU(),
    nn.Conv1d(128, 128, 8, stride=1, padding='same'),
    nn.ReLU(),
    nn.MaxPool1d(4, stride=4),
).to('cuda')

cnn2 = nn.Sequential(
    nn.Conv1d(10, 64, 400, stride=50),
    nn.ReLU(),
    nn.MaxPool1d(4, stride=4),
    nn.Dropout(0.5),
    nn.Conv1d(64, 128, 6, stride=1, padding='same'),
    nn.ReLU(),
    nn.Conv1d(128, 128, 6, stride=1, padding='same'),
    nn.ReLU(),
    nn.Conv1d(128, 128, 6, stride=1, padding='same'),
    nn.ReLU(),
    nn.MaxPool1d(2, stride=2),
).to('cuda')
output1 = cnn1(input_)
output2 = cnn2(input_)
out = torch.cat((output1, output2), dim = -1)
cnnout = out.transpose(1, 2)
print(cnnout.shape)

c:\Users\user\anaconda3\envs\test\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.Size([7547, 21, 128])


c:\Users\user\anaconda3\envs\test\lib\site-packages\torch\nn\modules\conv.py:294: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at  ..\aten\src\ATen\native\Convolution.cpp:660.)
  return F.conv1d(input, weight, bias, self.stride,


In [37]:
lstm = nn.LSTM(128, 128, num_layers = 2, bidirectional = True, batch_first = True).to('cuda')
encoder_outputs, encoder_state = lstm(cnnout)
print(encoder_outputs.shape)
print(encoder_state[0].shape)
print(encoder_state[1].shape)

torch.Size([7547, 21, 256])
torch.Size([4, 7547, 128])
torch.Size([4, 7547, 128])


In [67]:
y_train

array([[5, 3, 3, ..., 3, 3, 6],
       [5, 3, 3, ..., 3, 3, 6],
       [5, 0, 0, ..., 0, 0, 6],
       ...,
       [5, 0, 0, ..., 0, 0, 6],
       [5, 2, 2, ..., 2, 2, 6],
       [5, 0, 0, ..., 0, 0, 6]])

In [66]:
decoder_input = torch.zeros(y_train.shape[0], 7)  # Assuming <SOD> token representation
decoder_input[:, char2numY['<SOD>']] = 1

print(y_train.shape)
print(decoder_input.shape)
print(decoder_input)

(30191, 12)
torch.Size([30191, 7])
tensor([[0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.]])


In [ ]:
def train_step(encoder, decoder, inputs, target, optimizer, loss_object):
    encoder.train()
    decoder.train()

    optimizer.zero_grad()
    encoder_output, hidden_state = encoder(inputs)
    decoder_input = torch.zeros(target.shape[0], NUM_CLASSES+2)  # Assuming <SOD> token representation
    decoder_input[:, char2numY['<SOD>']] = 1
    loss = 0

    for t in range(SEQUENCE_LENGTH):
        pred, hidden_state = decoder(decoder_input, hidden_state, encoder_output)
        loss += loss_object(pred, target[:, t])
        decoder_input = F.one_hot(target[:, t], num_classes=NUM_CLASSES+2).float()

    loss.backward()
    optimizer.step()
    return loss.item()


In [25]:
class Attention(nn.Module):
    def __init__(self, **kargs):
        super(Attention, self).__init__()
        self.We = nn.Linear(2 * kargs['num_units'], 2 * kargs['num_units'],)
        self.Wh = nn.Linear(2 * kargs['num_units'], 2 * kargs['num_units'],)
        
    def forward(self, encoder_hidden, decoder_hidden):
        WE = self.We(encoder_hidden)
        decoder_hidden = torch.unsqueeze(decoder_hidden, 1)
        WH = self.Wh(decoder_hidden)
        x = torch.cat((WE, WH), dim = - 1)
        f = torch.tanh(x)
        alpha = torch.nn.functional.softmax(f, dim=-1)
        c = alpha * encoder_hidden
        c = torch.sum(c, axis=1)
        return c

In [42]:
NUM_CLASS= 7
kargs = {
    'epochs': 120,
    'batch_size': 20,
    'num_units': 128,
    'embed_size': 10,
    'input_depth': 3000,
    'n_channels': 100,
    'bidirectional': False,
    'use_attention': True,
    'lstm_layers': 2,
    'attention_size': 64,
    'beam_width': 4,
    'use_beamsearch_decode': False,
    'max_time_step': 10,
    'output_max_length': 10 + 2,
    'akara2017': True,
    'test_step': 5
}
We = nn.Linear(2 * kargs['num_units'], 2 * kargs['num_units']).to('cuda')
Wh = nn.Linear(2 * kargs['num_units'], 2 * kargs['num_units']).to('cuda')
lstm = nn.LSTM(2 * kargs['num_units'], 2 * kargs['num_units'], num_layers = kargs['lstm_layers'], bidirectional = True, batch_first = True).to('cuda')
classes = nn.Linear(2 * kargs['num_units'], NUM_CLASS).to('cuda')
softmax = nn.Softmax(dim=-1).to('cuda')

In [11]:
decoder_input = F.one_hot(torch.tensor(char2numY['<SOD>']), num_classes=7).float()
decoder_input = decoder_input.expand(input_.shape[0], -1)  # <SOD>로 시작
print(decoder_input.shape)

torch.Size([7547, 7])


In [38]:
h = torch.cat((encoder_state[0], encoder_state[1]), dim = -1)

In [41]:
encoder_outputs.shape

torch.Size([7547, 21, 256])

In [40]:
h.shape

torch.Size([4, 7547, 256])

In [36]:
encoder_outputs.shape

torch.Size([7547, 21, 512])

In [47]:
print(WE.shape)
print(WH.shape)

torch.Size([4, 7547, 256])
torch.Size([7547, 1, 21, 256])


In [51]:
encoder_outputs.shape

torch.Size([7547, 21, 256])

In [52]:
WE = We(h)
decoder_hidden = torch.unsqueeze(encoder_outputs, 1)
WH = Wh(encoder_outputs)
x = torch.cat((WE, WH), dim = -1)
f = torch.tanh(x)
alpha = torch.nn.functional.softmax(f, dim=-1)
c = alpha * encoder_outputs
c = torch.sum(c, axis=1)
c.shape

RuntimeError: Sizes of tensors must match except in dimension 0. Got 7547 and 4 (The offending index is 0)

In [28]:
c = attention(encoder_outputs, h)
print(c.shape)
x = torch.cat([c, decoder_input], dim=-1).unsqueeze(1)
print(x.shape)
x, h = lstm(x) # .squeeze(1)
print(h.shape)
prediction = softmax(classes(x))
print(prediction.shape)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (158487x512 and 256x256)

In [26]:
y_train.shape

(30191, 12)

In [21]:
print(('The training set after oversampling: ', classes))

for cl in classes:
    print((cl, len(np.where(y_train==char2numY[cl])[0])))

# training and testing the model
if (os.path.exists(checkpoint_dir) == False):
    os.mkdir(checkpoint_dir)

if (os.path.exists(output_dir) == False):
    os.makedirs(output_dir)

('The training set after oversampling: ', ['W', 'N1', 'N2', 'N3', 'REM'])
('W', 61734)
('N1', 58294)
('N2', 65294)
('N3', 58294)
('REM', 58294)


In [ ]:
def batch_data(x, y, batch_size):
    shuffle = np.random.permutation(len(x))
    start = 0
#     from IPython.core.debugger import Tracer; Tracer()()
    x = x[shuffle]
    y = y[shuffle]
    while start + batch_size <= len(x):
        yield x[start:start+batch_size], y[start:start+batch_size]
        start += batch_size

In [ ]:
import torch
import torch.nn as nn

lstm_layers = 2
lstm_units = 128

class Encoder(nn.Module):
    def __init__(self):
        super(Encoder, self).__init__()
        self.lstm = nn.LSTM(input_size=lstm_units, hidden_size=lstm_units, num_layers=lstm_layers, bidirectional=True, batch_first=True)
    
    def forward(self, data_input_embed):
        encoder_outputs, encoder_state = self.lstm(data_input_embed)
        return encoder_outputs, encoder_state

encoder = Encoder()
encoder_outputs, encoder_state = encoder(data_input_embed)

In [ ]:
import torch.nn as nn

class Decoder(nn.Module):
    def __init__(self, hparams):
        super(Decoder, self).__init__()
        if not hparams['bidirectional']:
            self.lstm = nn.LSTM(input_size=hparams['num_units'], hidden_size=hparams['num_units'], num_layers=hparams['lstm_layers'], batch_first=True)
        else:
            self.lstm = nn.LSTM(input_size=2*hparams['num_units'], hidden_size=2*hparams['num_units'], num_layers=hparams['lstm_layers'], batch_first=True)   

    def forward(self, x):
        decoder_outputs, decoder_state = self.lstm(x)
        return decoder_outputs, decoder_state

decoder = Decoder(hparams)
decoder_outputs, decoder_state = decoder(x)


In [ ]:
# seq-to-seq
class Encoder(tf.keras.layers.Layer):
    def __init__(self, vocab_size, embedding_dim, enc_units, batch_sz):
        super(Encoder, self).__init__()
        self.batch_sz = batch_sz
        self.enc_units = enc_units
        self.vocab_size = vocab_size 
        self.embedding_dim = embedding_dim          
        
        self.embedding = tf.keras.layers.Embedding(self.vocab_size, self.embedding_dim)
        self.gru = tf.keras.layers.GRU(self.enc_units,
                                       return_sequences=True,
                                       return_state=True,
                                       recurrent_initializer='glorot_uniform')

    def call(self, x, hidden):
        x = self.embedding(x)
        output, state = self.gru(x, initial_state = hidden)
        return output, state

    def initialize_hidden_state(self, inp):
        return tf.zeros((tf.shape(inp)[0], self.enc_units))

In [ ]:
# seq-to-seq
class Decoder(tf.keras.layers.Layer):
    def __init__(self, vocab_size, embedding_dim, dec_units, batch_sz):
        super(Decoder, self).__init__()
        
        self.batch_sz = batch_sz
        self.dec_units = dec_units
        self.vocab_size = vocab_size 
        self.embedding_dim = embedding_dim  
        
        self.embedding = tf.keras.layers.Embedding(self.vocab_size, self.embedding_dim)
        self.gru = tf.keras.layers.GRU(self.dec_units,
                                       return_sequences=True,
                                       return_state=True,
                                       recurrent_initializer='glorot_uniform')
        self.fc = tf.keras.layers.Dense(self.vocab_size)

        self.attention = BahdanauAttention(self.dec_units)
        
    def call(self, x, hidden, enc_output):
        context_vector, attention_weights = self.attention(hidden, enc_output)

        x = self.embedding(x)

        x = tf.concat([tf.expand_dims(context_vector, 1), x], axis=-1)

        output, state = self.gru(x)
        output = tf.reshape(output, (-1, output.shape[2]))
            
        x = self.fc(output)
        
        return x, state, attention_weights

In [28]:
decoder_input = torch.zeros(y_train.shape[0], 7)  # Assuming <SOD> token representation
decoder_input[:, char2numY['<SOD>']] = 1

print(decoder_input)

tensor([[0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.]])


In [ ]:
import torch
import torch.nn as nn

class Encoder(nn.Module):
    def __init__(self, cnn):
        super(Encoder, self).__init__()
        self.cnn = cnn
        self.lstm_f = nn.LSTM(128, 128, batch_first=True)
        self.lstm_b = nn.LSTM(128, 128, batch_first=True)
    
    def forward(self, inputs):
        x = [self.cnn(inputs[:, i]) for i in range(inputs.shape[1])]
        x = torch.stack(x, dim=1)
        f, (fh, _) = self.lstm_f(x)
        b, (bh, _) = self.lstm_b(x)
        x = torch.cat([f, b], dim=-1)
        h = torch.cat([fh, bh], dim=-1)
        return x, h

class Attention(nn.Module):
    def __init__(self, latent):
        super(Attention, self).__init__()
        self.We = nn.Linear(latent, latent)
        self.Wh = nn.Linear(latent, latent)
        self.tanh = nn.Tanh()
        self.softmax = nn.Softmax(dim=-1)
    
    def forward(self, encoder_hidden, decoder_hidden):
        WE = self.We(encoder_hidden)
        WH = self.Wh(decoder_hidden.unsqueeze(1))
        x = WE + WH
        f = self.tanh(x)
        alpha = self.softmax(f)
        c = alpha * encoder_hidden
        c = torch.sum(c, dim=1)
        return c

class Decoder(nn.Module):
    def __init__(self):
        super(Decoder, self).__init__()
        self.lstm_f = nn.LSTM(128 + 256, 128, batch_first=True)
        self.lstm_b = nn.LSTM(128 + 256, 128, batch_first=True)
        self.attention = Attention(256)
        self.classes = nn.Linear(256, 7)
        self.softmax = nn.Softmax(dim=-1)
    
    def forward(self, decoder_input, prev_decoder_hidden, encoder_hidden):
        c = self.attention(encoder_hidden, prev_decoder_hidden)
        x = torch.cat([c, decoder_input], dim=-1).unsqueeze(1)
        f, (fh, _) = self.lstm_f(x)
        b, (bh, _) = self.lstm_b(x)
        h = torch.cat([fh, bh], dim=-1)
        x = torch.cat([f, b], dim=-1).squeeze(1)
        prediction = self.softmax(self.classes(x))
        return prediction, h


loss_object = nn.CrossEntropyLoss()
opt = torch.optim.Adam(list(encoder.parameters()) + list(decoder.parameters()), lr=ETA)



def train_step(encoder, decoder, inputs, target, optimizer, loss_object):
    encoder.train()
    decoder.train()

    optimizer.zero_grad()
    encoder_output, hidden_state = encoder(inputs)
    decoder_input = torch.zeros(target.shape[0], NUM_CLASSES+2)  # Assuming <SOD> token representation
    decoder_input[:, char2numY['<SOD>']] = 1
    loss = 0

    for t in range(SEQUENCE_LENGTH):
        pred, hidden_state = decoder(decoder_input, hidden_state, encoder_output)
        loss += loss_object(pred, target[:, t])
        decoder_input = F.one_hot(target[:, t], num_classes=NUM_CLASSES+2).float()

    loss.backward()
    optimizer.step()
    return loss.item()

In [ ]:
import torch
import torch.nn.functional as F
from torch import nn, optim

def train_step(inputs):
    _X, _y = inputs
    _y = F.one_hot(torch.tensor(_y), num_classes=NUM_CLASSES+2).float()

    _loss = 0.

    optimizer.zero_grad()

    encoder_output, hidden_state = encoder(_X)

    decoder_input = F.one_hot(torch.tensor(char2numY['<SOD>']), num_classes=NUM_CLASSES+2).float()
    decoder_input = decoder_input.expand(_X.shape[0], -1)  # <SOD>로 시작

    for t in range(SEQUENCE_LENGTH):
        pred, hidden_state = decoder(decoder_input, hidden_state, encoder_output)
        _loss += loss_object(_y[:, t, :], pred)
        acc.update_state(acc_object(_y[:, t, :], pred))
        loss.update_state(_loss.item())
        decoder_input = _y[:, t, :].argmax(dim=1)

    _loss.backward()
    optimizer.step()


In [43]:
decoder_input = F.one_hot(torch.tensor(char2numY['<SOD>']), num_classes=7).float()
decoder_input = decoder_input.expand(X_train.shape[0], -1)  # <SOD>로 시작

In [38]:
import torch.nn.functional as F
F.one_hot(torch.tensor(y_train, dtype=torch.long), num_classes=7).float().shape

torch.Size([30191, 12, 7])

In [33]:
import torch.nn.functional as F

decoder_input = F.one_hot(torch.tensor(char2numY['<SOD>']), num_classes=NUM_CLASSES+2).float()
decoder_input = decoder_input.expand(_X.shape[0], -1)  # <SOD>로 시작

array([2, 4, 4, ..., 2, 1, 4])

In [ ]:
decoder_input = torch.zeros(target.shape[0], NUM_CLASSES+2)  # Assuming <SOD> token representation
decoder_input[:, char2numY['<SOD>']] = 1

In [1]:
import numpy as np

def mean_squared_error(y_true, y_pred):
    """
    Mean Squared Error 계산
    """
    return np.mean((y_true - y_pred) ** 2)

def classwise_mfe(y_true, y_pred, classes):
    """
    클래스별로 MFE 계산
    """
    mfe_dict = {}
    
    for c in classes:
        # 클래스 c에 속하는 샘플의 인덱스 추출
        indices = np.where(y_true == c)[0]
        
        # 클래스 c에 속하는 샘플의 예측값과 실제값 추출
        y_true_c = y_true[indices]
        y_pred_c = y_pred[indices]
        
        # 클래스 c에 속하는 샘플의 수
        C_i = len(indices)
        
        # MFE 계산 및 저장
        mfe_dict[c] = mean_squared_error(y_true_c, y_pred_c) / C_i
    
    return mfe_dict

def overall_mfe(y_true, y_pred, classes):
    """
    전체 MFE 계산
    """
    # 클래스별 MFE 계산
    class_mfe = classwise_mfe(y_true, y_pred, classes)
    
    # 전체 MFE 계산
    overall_mfe = np.mean(list(class_mfe.values()))
    
    return overall_mfe

# 예시 데이터
y_true = np.array([1, 1, 2, 2, 2, 3, 3, 3, 3])
y_pred = np.array([1.1, 1.2, 2.1, 2.0, 2.2, 3.2, 3.0, 3.1, 3.3])
classes = np.unique(y_true)

# 전체 MFE 계산
mfe_result = overall_mfe(y_true, y_pred, classes)

# 결과 출력
print(f"Overall MFE: {mfe_result}")

Overall MFE: 0.008935185185185187


In [31]:
y_train

array([[5, 2, 2, ..., 3, 2, 6],
       [5, 4, 4, ..., 4, 4, 6],
       [5, 4, 4, ..., 4, 4, 6],
       ...,
       [5, 2, 2, ..., 4, 4, 6],
       [5, 1, 1, ..., 1, 1, 6],
       [5, 4, 4, ..., 4, 4, 6]])

In [69]:
import pandas as pd
import enum
import os
import re
import json
import random
import matplotlib.pyplot as plt
import numpy as np

from preprocess import *
def dataload(index_inputs, index_outputs, index_targets):
    # 리스트 a의 길이
    length = len(index_inputs)

    # 랜덤하게 선택할 원소의 개수
    num_samples = length // 10

    # 랜덤하게 선택된 원소들의 인덱스
    val_index = random.sample(range(length), num_samples)
    train_index = [i for i in range(length) if i not in val_index]

    train_inputs=[index_inputs[i] for i in train_index]
    train_outputs=[index_outputs[i] for i in train_index]
    train_targets=[index_targets[i] for i in train_index]

    val_inputs=[index_inputs[i] for i in val_index]
    val_outputs=[index_outputs[i] for i in val_index]
    val_targets=[index_targets[i] for i in val_index]

    return train_inputs, train_outputs, train_targets, val_inputs, val_outputs, val_targets


In [70]:
DATA_IN_PATH = './data_in/'
DATA_OUT_PATH = './data_out/'
TRAIN_INPUTS = 'train_inputs.npy'
TRAIN_OUTPUTS = 'train_outputs.npy'
TRAIN_TARGETS = 'train_targets.npy'
DATA_CONFIGS = 'data_configs.json'

index_inputs = np.load(open(DATA_IN_PATH + TRAIN_INPUTS, 'rb'))
index_outputs = np.load(open(DATA_IN_PATH + TRAIN_OUTPUTS , 'rb'))
index_targets = np.load(open(DATA_IN_PATH + TRAIN_TARGETS , 'rb'))
prepro_configs = json.load(open(DATA_IN_PATH + DATA_CONFIGS, 'r'))

train_inputs, train_outputs, train_targets, val_inputs, val_outputs, val_targets = dataload(index_inputs, index_outputs, index_targets)


char2idx = prepro_configs['char2idx']
end_index = prepro_configs['end_symbol']
model_name = 'transformer'
vocab_size = prepro_configs['vocab_size']
BATCH_SIZE = 2
MAX_SEQUENCE = 25
EPOCHS = 30
learning_rate = 1e-4

kargs = {'model_name': model_name,
        'num_layers': 2,
        'd_model': 512,
        'num_heads': 8,
        'dff': 2048,
        'input_vocab_size': vocab_size,
        'target_vocab_size': vocab_size,
        'maximum_position_encoding': MAX_SEQUENCE,
        'end_token_idx': char2idx[end_index],
        'rate': 0.1,
        'epochs':EPOCHS,
        'batch_size':BATCH_SIZE,
        'train_index_inputs':train_inputs,
        'train_index_outputs':train_outputs,
        'train_index_targets':train_targets,
        'val_index_inputs':val_inputs,
        'val_index_outputs':val_outputs,
        'val_index_targets':val_targets,
        'learning_rate': learning_rate
        }

In [79]:
print(np.array(train_inputs).shape)
print(np.array(train_outputs).shape)
print(np.array(train_targets).shape)

(18, 25)
(18, 25)
(18, 25)


In [74]:
train_real = torch.tensor(kargs['train_index_targets'], dtype=torch.long).view(-1)
val_real = torch.tensor(kargs['val_index_targets'], dtype=torch.long).view(-1)
train_mask = ~torch.eq(train_real, 0)
val_mask = ~torch.eq(val_real, 0)
train_cost = []
val_cost = []

print(train_real.shape)
print(val_real.shape)
print(train_mask.shape)
print(val_mask.shape)

torch.Size([450])
torch.Size([50])
torch.Size([450])
torch.Size([50])


In [82]:
inp = torch.tensor(kargs['train_index_inputs'])
tar = torch.tensor(kargs['train_index_outputs'])

In [84]:
kargs['input_vocab_size']

111

In [105]:
y_train[0]

array([5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 6])

In [106]:
y_train = F.one_hot(torch.tensor(y_train, dtype=torch.long), num_classes=7).float()

In [108]:
y_train.shape

torch.Size([30191, 12, 7])

In [83]:
embedding = nn.Embedding(num_embeddings=kargs['input_vocab_size'], 
                               embedding_dim=512)

x = embedding(inp)
x.shape

torch.Size([18, 25, 512])